title: ./BoringOps.sh
subtitle: Shiny dulls. Boring endures.
description: "BoringOps is the discipline of building infrastructure that behaves predictably. No drama. No heroics. Just systems that work."
url: "https://boringops.sh"
author: BoringOps
twitter:
  username: boringops
social:
  name: BoringOps
  links:
    - https://github.com/boringops-hq

plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      permalink: /articles/:title/

collections:
  posts:
    output: true
    permalink: /articles/:title/
