title: BoringOps 
subtitle: Shiny breaks. Boring endures.
url: "https://boringops.sh"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin:  dark
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives

sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: single
      share: true

  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_excerpts: true
      author_profile: false
      share: true


# Configuration for jekyll-archives
jekyll-archives:
  enabled:
    - tags # Tells the plugin to generate pages for tags
  layout: tag_archive # Name of the layout file you will create
  permalinks:
    tag: '/tags/:name/' # Defines the URL structure (e.g., /tags/consistency/)
  collections:
    - articles

# Navigation
navigation:
  main: main
seo:
  type: "website"

header:
  nav:
    enable: true
  sticky: true

footer:
  content: "Â© 2025 BoringOps. This space intentionally left boring."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/boringops-hq/boringops-manifesto"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:hello@boringops.sh"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-N31L1R3FES"
    anonymize_ip: true

comments:
  share: 
    - twitter
    - linkedin
    - bluesky

